include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart" 
  strong-mode:
    implicit-casts: false 
    implicit-dynamic: false 

linter:
  rules:
    
    - avoid_print 
    - prefer_const_constructors 
    - prefer_final_locals 
    - prefer_final_fields 
    - avoid_unnecessary_containers 
    - avoid_redundant_argument_values 
    - avoid_renaming_method_parameters 
    - avoid_single_cascade_in_expression_statements 
    - avoid_types_as_parameter_names 
    - avoid_unused_constructor_parameters 
    - avoid_void_async 
    - cancel_subscriptions 
    - constant_identifier_names 
    - control_flow_in_finally 
    - directives_ordering 
    - empty_statements 
    - library_names 
    - no_duplicate_case_values 
    - no_logic_in_create_state 
    - prefer_adjacent_string_concatenation 
    - prefer_collection_literals 
    - prefer_conditional_assignment 
    - prefer_const_declarations 
    - prefer_contains 
    - prefer_final_in_for_each 
    - prefer_initializing_formals 
    - prefer_interpolation_to_compose_strings 
    - prefer_is_empty 
    - prefer_is_not_empty 
    - prefer_iterable_whereType 
    - prefer_null_aware_operators 
    - prefer_typing_uninitialized_variables 
    - prefer_void_to_null 
    - provide_deprecation_message 
    - require_trailing_commas 
    - sort_child_properties_last 
    - type_init_formals 
    - unawaited_futures 
    - unnecessary_brace_in_string_interps 
    - unnecessary_getters_setters 
    - unnecessary_lambdas 
    - unnecessary_null_checks 
    - unnecessary_overrides 
    - unnecessary_parenthesis 
    - unnecessary_statements 
    - unnecessary_this 
    - use_build_context_synchronously 
    - use_full_hex_values_for_flutter_colors 
    - use_key_in_widget_constructors 
    - use_rethrow_when_possible 
    - use_setters_to_change_properties 
    - use_string_buffers 
    - use_super_parameters 
    - valid_regexps 